name: goblintAnalysis

on:
  push:
  pull_request:

jobs:
  generate-Sarif:
    env:
      # ./analysisTarget/main.c needs to be replaced with ./analysisTarget/PATH_TO_FILE
      #for each file that is supposed to be analyzed.
      #This should be simplified to instead use the MakeFile of the repository.
      #the prefix  ./analysisTarget/ is removed in Goblint, so the location shows correctly in Github
      MAIN_NAME: './analysisTarget/main.c
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0 # matches opam lock file
          # don't add any other because they won't be used

    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
    steps:
      - name: Checkout Goblint repository
        uses: actions/checkout@v2
        with:
          repository: goblint/analyzer
          #this path needs to be changed to the main branch
          ref: integrationSarif
      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        env:
          # otherwise setup-ocaml pins non-locked dependencies
          # https://github.com/ocaml/setup-ocaml/issues/166
          OPAMLOCKED: locked
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        run: opam install . --deps-only --locked
      - name: Build
        run: ./make.sh nat
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path:  analysisTarget
      - name: Generate the Sarif output
        #cilly --gcc=/usr/bin/gcc-6 --merge main.c dumb.c -o merged --keepmerged
        # ./goblint --sarif -o GitHubSarif.sarif  ${{env.MAIN_NAME}} -R ./testCRepo/
        run: |
          ./goblint --sarif -o GitHubSarif.sarif ${{env.MAIN_NAME}}
      - name: Upload the generated Sarif File
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: GitHubSarif.sarif
